- src/main/backends/linux/hyprland/backend.ts
I have had an issue when running kando on hyprland.
```Failed to show menu: TypeError: Cannot read properties of undefined (reading 'x')```
I have checked the output of ```hyprctl activeworkspace``` and it didn't contain ```monitorID```
```
{
"id": 4,
"name": "4",
"monitor": "eDP-1",
"windows": 1,
"hasfullscreen": false,
"lastwindow": "0x55843f14e410",
"lastwindowtitle": "****"
}
```
This PR uses monitor name to identify which monitor the active workspace is in instead of monitorID. Which resolves the issue. However I do not have multiple monitors to test multi-monitor compatibility.
> Hyprland backend issue

- docs/changelog.md
- src/main/app.ts
> Properly restore input focus after closing the menu on Windows

- docs/installing.md
Very tiny change. I had some difficulty with not easily recognisable errors when running "npm install" to compile on macOS for the first time. After some tinkering I realised I needed to "cd /kando-directory-path" before running these commands which wasn't immediately obvious to me from the description. 
I think the reminder to cd into the Kando directory before running the two commands is helpful for those lacking experience like me who want to test new functionality by manually installing. 
I didn't make this change for windows and linux because I felt the lack of information is better than me giving incorrect information as I don't currently own a windows or linux machine to test installs there.
> :memo: Clarify manual install in "installing.md"

- docs/changelog.md
- docs/configuring.md
- src/@types/global.d.ts
- src/common/index.ts
- src/main/app.ts
- src/main/backends/backend.ts
- src/main/backends/linux/gnome/wayland/backend.ts
- src/main/backends/linux/hyprland/backend.ts
- src/main/backends/linux/hyprland/native/Native.cpp
- src/main/backends/linux/kde/wayland/backend.ts
- src/main/backends/linux/kde/x11/backend.ts
- src/main/backends/linux/wlroots/backend.ts
- src/main/backends/linux/x11/backend.ts
- src/main/backends/macos/backend.ts
- src/main/backends/windows/backend.ts
- src/renderer.ts
- src/renderer/editor/editor.scss
- src/renderer/editor/editor.ts
- src/renderer/editor/properties/properties.scss
- src/renderer/editor/properties/properties.ts
- src/renderer/editor/properties/shortcut-id-picker.ts
- src/renderer/editor/properties/shortcut-picker.ts
- src/renderer/editor/properties/templates/properties.hbs
- src/renderer/editor/properties/templates/shortcut-picker.hbs
- src/renderer/editor/toolbar/menus-tab.ts
- src/renderer/editor/toolbar/toolbar.scss
- src/renderer/editor/toolbar/toolbar.ts
- src/renderer/editor/toolbar/trash-tab.ts
- src/renderer/preload.ts
This adds the possibility to change the global shortcut ID on platforms which do not support direct binding of global shortcuts. For instance, on KDE/Wayland or on Hyprland, Kando can not directly bind global shortcuts. On those platforms, the menu editor shows a text field instead of the shortcut picker. Here you can enter a unique ID for the shortcut and then use the global shortcut settings of the desktop environment to bind the shortcut ID to a key combination.
> Suppot backends with no support for direct key bindings

- docs/changelog.md
- src/@types/global.d.ts
- src/common/index.ts
- src/main/app.ts
- src/renderer.ts
- src/renderer/menu/input-tracker.ts
- src/renderer/menu/menu.ts
- src/renderer/preload.ts
When a menu is opened in screen-center mode, turbo-mode is now disabled initially. This is to prevent accidental navigation when the menu is opened and a key is still pressed. Once all keyboard keys are released, turbo-mode can be activated by pressing and holding any key.
Related to #462.
> Fix turbo mode for centered menus

- .eslintrc.js
- docs/changelog.md
- src/common/key-codes.ts
- src/main/backends/index.ts
- src/main/backends/linux/kde/wayland/backend.ts
- src/main/backends/linux/portals/remote-desktop.ts
- src/renderer/editor/common/dnd-manager.ts
- src/renderer/menu/gesture-detection.ts
- src/renderer/menu/input-tracker.ts
- src/renderer/menu/menu.ts
This adds an [ESLint rule](https://typescript-eslint.io/rules/naming-convention/) which enforces naming conventions. This should make the code more consistent, easier to read, and easier to contribute to.
> Enforce naming convention

- docs/changelog.md
- src/common/index.ts
- src/renderer/editor/common/dnd-manager.ts
- src/renderer/editor/common/draggable.ts
- src/renderer/editor/common/drop-target.ts
- src/renderer/editor/common/editor-menu-item.ts
- src/renderer/editor/editor.ts
- src/renderer/editor/preview/preview-draggable.ts
- src/renderer/editor/preview/preview-drop-target.ts
- src/renderer/editor/preview/preview.ts
- src/renderer/editor/preview/style/index.scss
- src/renderer/editor/toolbar/drop-target-tab.ts
- src/renderer/editor/toolbar/menus-tab.ts
- src/renderer/editor/toolbar/stash-tab.ts
- src/renderer/editor/toolbar/style/index.scss
- src/renderer/editor/toolbar/toolbar-draggable.ts
- src/renderer/editor/toolbar/trash-tab.ts
Fro now on, if <kbd>Ctrl</kbd> or <kbd>Command</kbd> is pressed while dragging a menu or menu item in the editor, the item will be duplicated instead of moved.
> Drag-copy items

- docs/changelog.md
- docs/configuring.md
- src/common/index.ts
- src/main.ts
- src/main/app.ts
- src/main/settings.ts
The menu now behaves properly when scaled via <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>+</kbd>, <kbd>Ctrl</kbd>+<kbd>-</kbd>, and <kbd>Ctrl</kbd>+<kbd>0</kbd>. The scale factor is saved to and loaded from `config.json`. It's still a somewhat hidden feature, but once we have a general settings UI, this can be exposed via slider in the UI.
This resolves #490.
> HiDPI Zoom

- src/main/app.ts
- src/main/backends/macos/backend.ts
Fix for [#461](https://github.com/kando-menu/kando/issues/461).
> Fix Mac Workspaces Switching

- .github/workflows/checks.yml
- docs/README.md
- docs/changelog.md
- docs/config-files.md
- docs/configuring.md
- docs/contributing.md
- forge.config.ts
- package-lock.json
- package.json
- src/@types/global.d.ts
- src/common/icon-theme-registry.ts
- src/common/icon-themes/fallback-theme.ts
- src/common/icon-themes/user-icon-theme.ts
- src/main/app.ts
- src/renderer.ts
- src/renderer/editor/common/style/icon-container.scss
- src/renderer/editor/properties/icon-picker.ts
- src/renderer/editor/properties/style/icon-picker.scss
- src/renderer/editor/properties/templates/icon-picker.hbs
- src/renderer/menu/menu.scss
- src/renderer/menu/menu.ts
- src/renderer/preload.ts
This resolves #383.
To add your own icons to Kando, follow these steps:
1. Create a new `icon-themes` directory in Kando's configuration directory if it does not yet exist. Depending on your OS, this will be the following locations:
* <img height="14" width="26" src="https://cdn.simpleicons.org/windows" /> Windows: `%appdata%\kando\icon-themes`
* <img height="14" width="26" src="https://cdn.simpleicons.org/apple" /> macOS: `~/Library/Application Support/kando/icon-themes`
* <img height="14" width="26" src="https://cdn.simpleicons.org/linux/black" /> Linux: `~/.config/kando/icon-themes`
2. Create a new directory for your icon theme in the `icon-themes` directory. You can give it any name you like.
3. Add your icons to the new directory. The icons can be in various formats, but we recommend …
> Custom icon themes

- src/main/app.ts
For Mac, this small change is necessary so that **both** Kando settings and its menus appear in the current space right before showing.
> Move Kando Settings to Current Space

- src/renderer/menu/menu.ts
The principle is simple. `0123456789abcdefghijklmnopqrstuvwxyz` is used as an index to select a menu entry. In <https://github.com/Frenzie/nimbler> I also used uppercase should lowercase run out, but I don't believe that's necessary here.
0 closes the menu at the root or goes back one level when deeper down.
The remainder is automatically assigned a clockwise number, starting from the topmost item.
References #291. To close it, presumably some display is desired as well.
<hr>
> Implement keyboard navigation

- src/common/item-types/uri-item-action.ts
- src/common/item-types/uri-item-config.ts
Support info placeholders in URI item actions. For the issue [#571](https://github.com/kando-menu/kando/issues/571).
> support info-placeholders in URI item actions

- src/main/backends/index.ts
- src/main/backends/linux/cinnamon/x11/backend.ts
In the Cinnamon X11 environment, the Kando menu does not appear over full-screen applications because the window type is set to `'dock'`, which doesn't overlay full-screen windows.
- Changed the window type to `'normal'` to ensure the menu displays over full-screen apps.
- **Files Added**:
- `src/main/backends/linux/cinnamon/x11/backend.ts`: Added to handle the specific window type setting for Cinnamon X11.
- **Files Modified**:
- `src/main/backends/index.ts`: Integrated the new backend into the main backend index.
- **Multiple Monitors**: On systems with multiple monitors, when the cursor is on the primary display, the Kando menu appears on a different display. Further investigation is required to fix this behavior.
- Tested with full-screen applications (Firefox, Xournal++). The menu …
> 🐛 Fix Cinnamon/X11 window type to display over full-screen apps

- docs/changelog.md
- docs/configuring.md
- docs/menu-themes.md
- src/@types/global.d.ts
- src/common/icon-theme-registry.ts
- src/common/icon-themes/file-icon-theme.ts
- src/common/index.ts
- src/main/app.ts
- src/renderer.ts
- src/renderer/preload.ts
This resolves #614.
Icon themes are now also loaded from `resources/app/.webpack/renderer/assets/icon-themes/` in the installation directory. This can be interesting if you are packaging icon themes using a package manager. However, as an end user, you should not put your icon themes there, as they might be overwritten during an update.
You can now create a symbolic link to an icon theme in the `icon-themes` directory and Kando will load the icons from the linked directory.
> Load icons from installation directory.

- docs/installing.md
some kando configs have opacity, and kando have opacity to, platform-specific notes haven't "windowrule = opaque, kando" to disable opacity in kando
> Opacity fix

- docs/changelog.md
- docs/config-files.md
- src/renderer/editor/editor.scss
- src/renderer/editor/preview/preview.ts
- src/renderer/editor/preview/utils.ts
- src/renderer/editor/properties/icon-picker.ts
- src/renderer/editor/properties/properties.ts
- src/renderer/editor/properties/style/index.scss
- src/renderer/editor/properties/templates/icon-picker.hbs
- src/renderer/editor/toolbar/add-items-tab.ts
- src/renderer/editor/toolbar/menus-tab.ts
- src/renderer/editor/toolbar/templates-tab.ts
- src/renderer/editor/toolbar/trash-tab.ts
- src/renderer/icon-themes/base64-theme.ts
- src/renderer/icon-themes/emoji-theme.ts
- src/renderer/icon-themes/fallback-theme.ts
- src/renderer/icon-themes/file-icon-theme.ts
- src/renderer/icon-themes/icon-list-theme.ts
- src/renderer/icon-themes/icon-pickers/base64-picker.ts
- src/renderer/icon-themes/icon-pickers/icon-list-picker.ts
- src/renderer/icon-themes/icon-pickers/style/base64-picker.scss
- src/renderer/icon-themes/icon-pickers/style/icon-list-picker.scss
- src/renderer/icon-themes/icon-pickers/templates/icon-list-picker.hbs
- src/renderer/icon-themes/icon-theme-registry.ts
- src/renderer/icon-themes/material-symbols-theme.ts
- src/renderer/icon-themes/simple-icons-colored-theme.ts
- src/renderer/icon-themes/simple-icons-theme.ts
- src/renderer/menu/menu-theme.ts
This adds a new icon theme: "Base64". This allows you to directly embed base64 encoded images. This will be especially helpful for menus which are dynamically generate via some sort of API in the future.
> Add support for base64 icons

- docs/changelog.md
- docs/config-files.md
- docs/configuring.md
- src/common/index.ts
- src/main/app.ts
- src/main/settings.ts
- src/renderer.ts
- src/renderer/editor/editor.ts
- src/renderer/editor/sidebar/style/index.scss
- src/renderer/editor/toolbar/style/index.scss
- src/renderer/menu/menu.ts
This adds the possibility to hide sidebar and editor buttons. You can now add
```json
"editorOptions": {
"showSidebarButtonVisible": false,
"showEditorButtonVisible": false
}
```
to your `config.json` to hide the show-sidebar and the show-editor buttons respectively. They will still be clickable, so you can still use them if you aim carefully.
This resolves #419.
> Hide chrome

- docs/changelog.md
- forge.config.ts
This resolves #502 in a very ugly way. But currently I do not see a good alternative.
> Add '--define _build_id_links none' to the rpmbuild command

- docs/changelog.md
- src/common/item-types/command-item-action.ts
This makes sure that processes launched with the command action are detached. This way, they are not killed if Kando exits.
> :wrench: Detach child processes

- .github/workflows/deploy.yml
- .github/workflows/pull_request.yml
- docs/changelog.md
macOS 12 runners are now deprecated.
> Use macos 13 for building and deploying

- src/common/index.ts
- src/main/app.ts
- src/main/settings.ts
This PR causes Kando to correctly handle the situation where config files are read-only or the user has no permission to write to them.
When a config file is in such a state we log the error to stdout and send a notification to warn the user their work was not saved. We also save the new config to `os.tmpdir()/kando/{config.json, menus.json}` For easy reference (for example for inclusion into a nix configuration)
Finally it is also possible to set `ignoreWriteProtectedConfigFiles: true` in `config.json` to silence the notification and stdout warning (but still write to /tmp/kando)
fixes #740
> Handle read-only config files neatly

- .github/workflows/deploy_to_winget.yml
This adds a workflow which should update the [Kando manifest](https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/KandoMenu/Kando/1.7.0) of winget after an release.
If this really works, we will see after the next release 😄
> Add winget deploy workflow

- docs/changelog.md
- src/common/key-codes.ts
This adds a missing key code for <kbd>Numpad Subtract</kbd> on Windows.
> Fix simulating numpad subtract

- docs/changelog.md
- locales/en/translation.json
- src/common/item-action-registry.ts
- src/common/item-config-registry.ts
- src/common/item-type-registry.ts
- src/common/item-types/file-item-action.ts
- src/common/item-types/file-item-config.ts
- src/common/item-types/file-item-type.ts
You can use this new item type to open files or directories with the default application. You could do this with the Command or Open URI item types before, but this new item type is more intuitive. Also, the Open URI type had issues with non-ASCII characters in the file path, which should be fixed with this new item type (#798).
> Add new file item type

- docs/changelog.md
- locales/en/translation.json
- src/common/index.ts
- src/main/app.ts
- src/renderer/editor/properties/advanced-options-picker.ts
- src/renderer/editor/properties/templates/advanced-options-picker.hbs
- src/renderer/menu/input-methods/pointer-input.ts
- src/renderer/menu/menu.ts
This adds a very advanced interaction mode: **Hover Mode**! This is like turbo mode or marking mode, but without the need to press any key or button! This is very advanced as it can easily lead to wrong selections. But at the same time, it is the fastest selection mode available!
This fixes #303.
> Add hover mode

- assets/menu-themes/clean-circle/theme.css
- assets/menu-themes/default/theme.css
- assets/menu-themes/neon-lights/theme.css
- assets/menu-themes/rainbow-labels/theme.css
- docs/changelog.md
- src/main/app.ts
- src/renderer/menu/input-methods/pointer-input.ts
- src/renderer/menu/menu.ts
You can now set `"menuOptions": {"hoverModeNeedsConfirmation": true}` in your `config.json` to tweak the hover mode so that it requires a final click to select an item. This is a bit slower, but it can prevent accidental selections.
> Add optional confirmation click to hover mode

- docs/changelog.md
- src/main/backends/linux/portals/remote-desktop.ts
With this PR, Kando tries to use version 2 of the remote desktop portal which allows restoring the session after the application has been restarted. This means, no annoying dialogs anymore!
> Restore remote desktop sessions on KDE Wayland

- forge.config.ts
- locales/en/translation.json
- src/renderer/icon-themes/base64-theme.ts
- src/renderer/icon-themes/icon-pickers/base64-picker.ts
- Update `forge.config.ts` configuration to unblock `https:` resources during development
- Rename `Base64` option to `Base64 or URL`
- Mention URL support in Base64 picker's placeholder
- Update code comments: `Base64 images` -> `Base64 images or URLs`
> Mention URL support in base64 picker

- .editorconfig
- .gitattributes
Closes #874 
I didn't reformat all files to break the git-blame.
The new configuration will automatically be applied to our developers' editor for future edits.
> Add `.editorconfig` and `.gitattributes`

- src/renderer/icon-themes/icon-pickers/templates/icon-list-picker.hbs
Fixed an unexpected input size change.
|Before|After|
|:-:|:-:|
|![](https://github.com/user-attachments/assets/e90b5046-5fc5-4c83-8482-82f3be85d918)|![](https://github.com/user-attachments/assets/d013fd7b-b69a-4bc9-8286-c95b8c11c238)|
> Fix input size of icon picker

- src/settings-renderer/components/CollectionList.module.scss
- src/settings-renderer/components/CollectionList.tsx
Fix the UI issue on the collection list.
|Before|After|
|:-:|:-:|
|![](https://github.com/user-attachments/assets/a8bbab27-8f99-4ebe-963e-d1fd0bee257e)|![](https://github.com/user-attachments/assets/c383760e-d632-4868-b752-fd0c170d7f36)|
> Add safe-area-top to collection list

- src/common/index.ts
- src/menu-renderer/index.ts
- Add support for default 'open settings' OS dependent hotkeys.
- Add setting to enable or disable the previously mentioned hotkeys.
- Move `getBackendInfo` function to the common API and refactor where necessary.
> 🎉 Add default settings hotkey support for settings window (#470).

- docs/changelog.md
- forge.config.ts
- src/main/index.ts
This is a draft PR for showing how to implement the [deep link](https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app) support. The deep link will be:
```
kando://menu?name=Example%20Menu
```
Putting the menu name parameter in the search parameter is better for parsing special cases like CJK characters and emojis.
@Schneegans I'm not sure my code was added to the correct place. And it should also have more validation before calling the `kando.showMenu()`, e.g., checking the existence of the menu name. Do you have any suggestions?
> Add support for deep links

- src/common/icon-themes/simple-icons-theme.ts
The icon slug may have the underscore character, like the Uniqlo (JP) icon:
You can try searching `uniqlo`; it should list two Uniqlo icons.
> Fix Simple Icons regex pattern

- package-lock.json
- package.json
- src/common/icon-themes/simple-icons-colored-theme.ts
- src/common/icon-themes/simple-icons-theme.ts
- src/settings-renderer/components/common/GridIconPicker.tsx
This previous tooltip can only display slugs. ~~I've used a temporary solution to read the icon title from the `simple-icons` package.~~
I've used https://github.com/simple-icons/simple-icons-font/pull/226 (Simple Icons v15), we can read the title from the `simple-icons-font` built-in JSON file instead.
> :wrench: Fix tooltip content for Simple Icons Theme

- docs/changelog.md
- src/menu-renderer/sound-theme.ts
Before, only changes to the `theme.json` file were reloaded when the sound theme was reloaded. Now, all sound files are reloaded as well.
> Fix reloading sound themes

- docs/changelog.md
- src/common/icon-themes/file-icon-theme.ts
If multiple SVG icons with the same CSS classes were used in the same menu, the styles clashed resulting in wrong colors.
> Fix SVGs with embedded CSS

- docs/changelog.md
- package-lock.json
- package.json
- src/common/common-window-api.ts
- src/common/icon-themes/fallback-theme.ts
- src/common/icon-themes/icon-theme-registry.ts
- src/common/icon-themes/system-theme.ts
- src/common/index.ts
- src/main/app.ts
- src/main/backends/backend.ts
- src/main/backends/linux/backend.ts
- src/main/backends/linux/gnome/wayland/backend.ts
- src/main/backends/linux/kde/wayland/backend.ts
- src/main/backends/linux/wlroots/backend.ts
- src/main/backends/linux/x11/backend.ts
- src/main/menu-window.ts
- src/menu-renderer/index.ts
This PR allows you to use your Linux system icons as icons for menu items. This is still somewhat experimental, but it should work on most desktop environments. Feel free to test it and report any issues you encounter!
> System icons

- docs/changelog.md
- src/main/index.ts
This should make the app show the settings when a second instance of the app is started on macOS.
> Fix issue #1065
