src/menu/gesture-detection.ts, src/menu/menu.ts
=> Gesture detection

src/app.ts, src/menu/menu.scss, src/menu/menu.ts, src/menu/theme.scss, src/renderer.ts
=> Add subtle fade-in / fade-out animations

src/app.ts, src/index.html, src/index.scss, src/menu/menu.scss, src/menu/menu.ts, src/menu/theme.scss, src/preload.ts, src/renderer.d.ts, src/renderer.ts
=> Hide Disclaimer

src/menu/menu.ts
This resolves #5 and #6. While there are still some issues (especially with the positioning of the menu), the basic interaction works pretty well.
=> Touch support

binding.gyp, src/app.ts, src/backend/backend.ts, src/backend/gnome/backend.ts, src/backend/win32/backend.ts, src/backend/win32/native/active_window.cpp, src/backend/win32/native/active_window.hpp, src/backend/win32/native/main.cpp, src/backend/win32/native/move_pointer.cpp, src/backend/win32/native/move_pointer.hpp, src/backend/x11/backend.ts, src/backend/x11/native/active_window.cpp, src/backend/x11/native/active_window.hpp, src/backend/x11/native/main.cpp, src/menu/menu.ts, src/preload.ts, src/renderer.d.ts, src/renderer.ts
=> Warp pointer

forge.config.ts, src/index.ts
=> Fail notification

docs/changelog.md, src/main/app.ts, src/renderer.ts, src/renderer/editor/sidebar/sidebar.ts, src/renderer/editor/sidebar/templates/button-tab.hbs, src/renderer/editor/theme.scss, src/renderer/preload.ts
This adds an example action which runs any given shell command. You can type a command into a text entry and Kando will execute it when you press enter. This will be one of the most basic actions in Kando.
=> Command Action

docs/changelog.md, package-lock.json, package.json, src/main.ts, src/main/app.ts
This resolves #278. You can now open menus via the `--menu <name>` command line argument.
=> Initial CLI

docs/changelog.md, src/common/index.ts, src/main/app.ts, src/main/settings.ts, src/renderer.ts, src/renderer/editor/editor.ts, src/renderer/editor/sidebar/sidebar.ts, src/renderer/editor/sidebar/templates/sidebar.hbs, src/renderer/preload.ts, test/settings.spec.ts
This PR exposes the app settings to the renderer process. As a first step, the visibility of the sidebar is now persistent between sessions.
=> App Settings

docs/changelog.md, src/main/backends/win32/native/simulate_key.cpp
=> Add support for extended scan codes on Windows

docs/configuring.md, docs/installing.md
`%APPDATA%\Roaming` -> `%APPDATA%]`
&
`%APPDATA%\Local` -> `%LOCALAPPDATA%`
=> 📝Make two Windows paths using variables valid

docs/changelog.md, src/renderer/editor/common/item-dragger.ts, src/renderer/editor/preview/preview.ts, src/renderer/editor/preview/utils.ts
This significantly improves the algorithm which calculates the drop location when dragging an item in the menu editor's preview. There are still some weird edge cases especially in the presence of fixed angles, but it should work much better now.
=> Better drag drop

docs/changelog.md, src/renderer/editor/common/item-dragger.ts, src/renderer/editor/editor.scss, src/renderer/editor/preview/preview.scss, src/renderer/editor/preview/templates/preview.hbs, src/renderer/editor/properties/properties.scss, src/renderer/editor/properties/templates/properties.hbs, src/renderer/editor/sidebar/templates/sidebar.hbs, src/renderer/editor/theme.scss, src/renderer/editor/toolbar/templates/empty-tab.hbs, src/renderer/editor/toolbar/templates/menus-tab.hbs, src/renderer/editor/toolbar/templates/toolbar.hbs, src/renderer/editor/toolbar/toolbar.scss, src/renderer/editor/toolbar/toolbar.ts, src/renderer/index.scss
This makes the layout and sizing of menu editor components depend on the window size. This way, the editor will look much better on small and large screens.
=> Better UI sizing

docs/changelog.md, docs/configuring.md, src/renderer/editor/common/icon-container.scss, src/renderer/editor/common/themed-icon.ts, src/renderer/editor/preview/preview.scss, src/renderer/math/index.ts, src/renderer/menu/menu-node.ts, src/renderer/menu/menu.scss, src/renderer/menu/menu.ts
This refactors some code and adds support for Emojis as icons! Also, menu icons are now cropped to a circle which may help resolving #364.
=> Emoji icons

docs/changelog.md, src/renderer/menu/center-text.ts, src/renderer/menu/menu.scss, src/renderer/menu/menu.ts
=> Better center text

docs/changelog.md, src/main/app.ts
=> Workaround for #375

src/renderer/editor/common/dragger.ts, src/renderer/editor/common/item-dragger.ts, src/renderer/editor/common/toolbar-item-dragger.ts, src/renderer/editor/preview/preview.ts, src/renderer/editor/toolbar/menus-tab.ts, src/renderer/editor/toolbar/templates/toolbar.hbs, src/renderer/editor/toolbar/toolbar.scss, src/renderer/editor/toolbar/toolbar.ts, src/renderer/editor/toolbar/trash-tab.ts
This refactors some common code to a new class.
=> Recycle item dragger

docs/changelog.md, src/common/index.ts, src/main/app.ts, src/renderer/editor/common/item-dragger.ts, src/renderer/editor/common/toolbar-item-dragger.ts, src/renderer/editor/editor.ts, src/renderer/editor/preview/preview-item-dragger.ts, src/renderer/editor/preview/preview.ts, src/renderer/editor/preview/utils.ts, src/renderer/editor/toolbar/menus-tab.ts, src/renderer/editor/toolbar/stash-tab.ts, src/renderer/editor/toolbar/templates/menus-tab.hbs, src/renderer/editor/toolbar/templates/stash-trash-tab.hbs, src/renderer/editor/toolbar/toolbar-item-dragger.ts, src/renderer/editor/toolbar/toolbar.scss, src/renderer/editor/toolbar/toolbar.ts, src/renderer/editor/toolbar/trash-tab.ts
This adds the stash area to the toolbar. You can temporarily store menu items there.
=> Add the Stash

docs/changelog.md, src/@types/global.d.ts, src/main/app.ts, src/renderer.ts, src/renderer/preload.ts
=> Tray settings

docs/changelog.md, src/main.ts, src/main/app.ts
This resolves #393 to a certain degree. I decided to show a desktop notification instead and add a command line option to show the menu editor.
=> Show-editor command line option

docs/changelog.md, src/renderer/editor/editor.scss, src/renderer/editor/properties/icon-picker.scss, src/renderer/editor/properties/properties.scss, src/renderer/editor/properties/properties.ts, src/renderer/editor/properties/templates/properties.hbs
This PR adds the option to toggle a menu's open-at-screen-center property via the editor.
=> Open-at-Pointer Checkbox

docs/changelog.md, src/main/backends/linux/wlroots/native/Native.cpp, src/main/backends/linux/wlroots/native/Native.hpp
=> Resolve issue #417

docs/changelog.md, src/@types/global.d.ts, src/main/app.ts, src/main/backends/backend.ts, src/main/backends/linux/gnome/wayland/backend.ts, src/main/backends/linux/x11/backend.ts, src/main/backends/macos/backend.ts, src/main/backends/windows/backend.ts, src/renderer.ts, src/renderer/editor/common/item-dragger.ts, src/renderer/editor/editor.scss, src/renderer/editor/editor.ts, src/renderer/editor/properties/icon-picker.scss, src/renderer/editor/properties/icon-picker.ts, src/renderer/editor/properties/properties.scss, src/renderer/editor/properties/properties.ts, src/renderer/editor/properties/shortcut-picker.scss, src/renderer/editor/properties/shortcut-picker.ts, src/renderer/editor/properties/templates/properties.hbs, src/renderer/editor/properties/templates/shortcut-picker.hbs, src/renderer/editor/toolbar/menus-tab.ts, src/renderer/preload.ts
This adds an interactive menu shortcut picker to the menu editor.
=> Shortcut Picker

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, docs/changelog.md
=> Issue templates

docs/changelog.md, docs/configuring.md, package-lock.json, package.json, src/common/item-action-registry.ts, src/common/item-config-registry.ts, src/common/item-type-registry.ts, src/common/item-types/hotkey-item-type.ts, src/common/item-types/macro-item-action.ts, src/common/item-types/macro-item-config.ts, src/common/item-types/macro-item-type.ts, src/renderer/editor/common/style/scrollbox.scss, src/renderer/editor/properties/hotkey-picker.ts, src/renderer/editor/properties/macro-picker.ts, src/renderer/editor/properties/shortcut-id-picker.ts, src/renderer/editor/properties/shortcut-picker.ts, src/renderer/editor/properties/style/text-picker.scss, src/renderer/editor/properties/templates/text-picker-option.hbs, src/renderer/editor/properties/text-picker.ts
This adds a new item type: Keyboard macros!
=> Keyboard Macros

docs/changelog.md, docs/configuring.md, src/@types/global.d.ts, src/common/index.ts, src/main/app.ts, src/renderer.ts, src/renderer/editor/editor.scss, src/renderer/editor/editor.ts, src/renderer/editor/properties/condition-picker.ts, src/renderer/editor/properties/properties.ts, src/renderer/editor/properties/style/index.scss, src/renderer/editor/properties/templates/checkbox-option.hbs, src/renderer/editor/properties/templates/condition-picker.hbs, src/renderer/editor/properties/templates/properties.hbs, src/renderer/preload.ts
This adds menu conditions! For instance, you can show a menu only if a specific application is focused or if the mouse is in a specific region of the screen. Thanks a ton to [@ClearStaff](https://github.com/ClearStaff) for many contributions to this feature!
=> Menu Conditions

README.md, docs/installing.md
I added Kando to Homebrew for macOS users: https://github.com/Homebrew/homebrew-cask/pull/180257
=> Add Brew Installation to README

docs/usage.md
Added GestureSign to list of Windows tools for opening a Kando menu.
=> Add GesutreSign to list of Windows tools in usage.md

docs/installing.md
tada, i've forgotten how to use github, but now it seems to be fine
=> Platform Specific notes for dusk wm

docs/changelog.md, src/@types/global.d.ts, src/main/app.ts, src/main/backends/backend.ts, src/main/backends/linux/gnome/wayland/backend.ts, src/main/backends/linux/hyprland/backend.ts, src/main/backends/linux/hyprland/native/Native.cpp, src/main/backends/linux/hyprland/native/index.ts, src/main/backends/linux/kde/wayland/backend.ts, src/main/backends/linux/wlroots/backend.ts, src/main/backends/linux/x11/backend.ts, src/main/backends/macos/backend.ts, src/main/backends/windows/backend.ts, src/renderer.ts, src/renderer/preload.ts
This resolves #585 by unbinding only the shortcut for the menu which is currently about to be shown.
=> Fast-Switching Menus

docs/changelog.md, locales/en/translation.json, src/@types/global.d.ts, src/common/index.ts, src/main/app.ts, src/main/backends/linux/cinnamon/x11/backend.ts, src/main/backends/linux/gnome/wayland/backend.ts, src/main/backends/linux/hyprland/backend.ts, src/main/backends/linux/kde/wayland/backend.ts, src/main/backends/linux/kde/x11/backend.ts, src/main/backends/linux/x11/backend.ts, src/main/backends/macos/backend.ts, src/main/backends/windows/backend.ts, src/renderer.ts, src/renderer/editor/editor.ts, src/renderer/editor/sidebar/sidebar.ts, src/renderer/editor/sidebar/templates/dev-tab.hbs, src/renderer/preload.ts
The sidebar now shows some version information in the development tab. This includes the version of Kando, the version of Electron, and the currently used backend.
=> Version info

src/main/backends/linux/hyprland/backend.ts, src/main/backends/linux/kde/wayland/backend.ts
This adds some tweaks and fixes to make Kando work inside a Flatpak container.
=> Flatpak support

docs/changelog.md, locales/en/translation.json, src/main/app.ts
=> Pause shortcuts

.github/workflows/checks.yml, .github/workflows/deploy.yml, .github/workflows/pull_request.yml, .github/workflows/test_deploy.yml, docs/changelog.md, tools/make-app-image.sh
This uploads the test builds for each pull request as temporary artifact.
=> Upload test deploy artifacts

docs/changelog.md, src/main/app.ts
This could potentially fix #792.
=> Initialize the window lazily

docs/changelog.md, src/main/example-menus/windows.json
=> Do not use explorer command in windows default menu

docs/changelog.md, src/main/app.ts, src/renderer/menu/input-methods/gamepad-input.ts, src/renderer/menu/menu.ts
- Add setting to enable / disable the gamepad input.
=> :tada: Add setting to enable/disable gamepad input (#754).

README.md
Hi Simon, do you want to try the new style?
[![kofi](https://img.shields.io/badge/Donate-on_Ko--fi-ff5e5b?logo=ko-fi)](https://ko-fi.com/schneegans) [![github](https://img.shields.io/badge/Donate-on_GitHub-purple?logo=github)](https://github.com/sponsors/Schneegans) [![paypal](https://img.shields.io/badge/Donate-on_PayPal-009cde?logo=paypal)](https://www.paypal.com/donate/?hosted_button_id=3F7UFL8KLVPXE) [![crypto](https://img.shields.io/badge/Donate-some_Crypto-f7931a?logo=bitcoin)](https://schneegans.cb.id)
[![kofi](https://img.shields.io/badge/Donate%20on%20Ko--fi-FF6433?logo=kofi&logoColor=fff&style=flat-square)](https://ko-fi.com/schneegans) [![github](https://img.shields.io/badge/Donate%20on%20GitHub-EA4AAA?logo=githubsponsors&logoColor=fff&style=flat-square)](https://github.com/spon …
=> Update donation badges

src/settings-renderer/components/menu-preview/MenuPreview.module.scss
|Before|After|
|:-:|:-:|
|![](https://github.com/user-attachments/assets/5a50c4ea-3d45-41f3-a31e-66d44dd9ee68)|![](https://github.com/user-attachments/assets/23a1c3b2-450b-407e-b691-821d740b4d5c)|
=> :lipstick: Keep the arrow icon in backlink button visually centered

src/common/icon-themes/simple-icons-colored-theme.ts
Related to #934
I just missed the colored icon theme.
=> :bug: Fix search colored icons with special characters

package-lock.json
I just updated the version field by using `npm install`.
=> :wrench: Fix version in lockfile

src/settings-renderer/components/common/Base64IconPicker.tsx
Fix the format pattern:
```diff
-data:image/svg;base64,...
+data:image/svg+xml;base64,...
```
=> :wrench: Fix base64 example string

README.md
- This PR fixed the broken `Checks` badge and changed the badge style to match shields.io's, making all badges consistent.
- There is a trailing space at the end of line 23. I just fixed it.
=> :lipstick: Polish GitHub Actions badges

docs/changelog.md, src/main/app.ts, src/main/index.ts, src/main/menu-window.ts, src/main/settings-window.ts
=> Add close action to hidden menu bar

assets/menu-themes/clean-circle/theme.json5, assets/menu-themes/default/theme.json5, assets/menu-themes/neon-lights/theme.json5, docs/changelog.md, src/menu-renderer/center-text.ts, src/menu-renderer/index.scss, src/menu-renderer/menu.ts
Fixes #881 and makes the center text wrap inside a circular shape.
=> Implement proper circle text wrapping
